% No example data is provided, so this is just a high-level exmaple of how
% to use the onset detection code & the jackknife error estimation code

% Assume that you have some ERP data of length K for N subjects and this
% is stored in a matrix of size [N,K]. Call this variable allERPs.

n = 10; % example number of subjects
k = 500; % example number of datapoints in the ERP trace
allERPs = rand(n,k); % random data for the purpose of running this script only

timeSec = linspace(0,10,k); % example vector of ERP time values in seconds
timeLabel = [-1.*ones(1,50), ones(1,450)]; % hypothetical labels specifying the 
                                           % baseline period with -1 during the first 50 time points (1 sec)
                                           
allERPs(:,timeLabel==-1) = .3.*allERPs(:,timeLabel==-1); % make the ERP data 
                                           % smaller in the baseline period for the purpose of running this script only

% add subject variability for the purpose of this script only:                                        
for subj = 1:n
    allERPs(subj,50:(50+10*subj)) = .3.*allERPs(subj,50:(50+10*subj));
end

% now find the onset time for the mean ERP:
onsetTimeMean = findOnsetTime(mean(allERPs),timeSec,timeLabel,'OsmanEtAl1992','makePlot',true,'allSeries',allERPs,'windowLenSec',0.025,'printInfo',true)

% now calculate the onset times for each leave-one-out dataset of mean
% ERPs:
onsetTimesSubsets = nan(1,n);
for subj = 1:n
    notIx = ones(1,n);
    notIx(subj) = 0;
    notIx = logical(notIx);
    crntMean = nanmean(allERPs(notIx,:));
    onsetTimesSubsets(subj) = findOnsetTime(crntMean,timeSec,timeLabel,'OsmanEtAl1992','makePlot',false,'allSeries',allERPs,'windowLenSec',0.025,'printInfo',false);
end
% calculate the jackknifed error estimate for the subset onset times:
onsetErr = jackKnifeErr(onsetTimesSubsets)

% now add shaded error range to the plot generated by findOnsetTime():
h = fill([onsetTimeMean-onsetErr onsetTimeMean+onsetErr onsetTimeMean+onsetErr onsetTimeMean-onsetErr],...
    [min(ylim) min(ylim) max(ylim) max(ylim)],'b');
set(h,'LineStyle','none','FaceAlpha',0.2);

text(onsetTimeMean+onsetErr,mean(ylim),sprintf('onset=%2.2f±%2.2f sec',onsetTimeMean,onsetErr),'Color','b');